---
  - name: Creates directory
    file:
      path: /home/ubuntu/backend
      state: directory

  - name: "move backend files to server."
    synchronize:
      src: ../../backend
      dest: /home/ubuntu

  - name: "install package dependencies"
    shell: |
      cd /home/ubuntu/backend
      npm install
  - name: "build package"
    shell: |
      cd /home/ubuntu/backend
      npm run build
  - name: "run migrations again"
    shell: |
      cd /home/ubuntu/backend
      npm run migrations
  - name: Executing node
    become: true
    shell: |
      cd /home/ubuntu/backend
      . development.env
      pm2 start npm --name backend -- start
      pm2 ls